name: experiment_env
channels:
  - conda-forge/label/gcc7
  - bioconda
  - anaconda
  - r
  - conda-forge
  - defaults
dependencies:
  - python=3.5.6
  - bioconductor-annotate
  - bioconductor-annotationdbi
  - bioconductor-annotationforge
  - bioconductor-biobase
  - bioconductor-biocgenerics
  - bioconductor-biocinstaller
  - bioconductor-biocparallel
  - bioconductor-biomart
  - bioconductor-biostrings
  - bioconductor-bsgenome
  - bioconductor-category
  - bioconductor-delayedarray
  - bioconductor-deseq2
  - bioconductor-diffbind
  - bioconductor-edger
  - bioconductor-genefilter
  - bioconductor-geneplotter
  - bioconductor-genomeinfodb
  - bioconductor-genomeinfodbdata
  - bioconductor-genomicalignments
  - bioconductor-genomicfeatures
  - bioconductor-genomicranges
  - bioconductor-go.db
  - bioconductor-gostats
  - bioconductor-graph
  - bioconductor-gseabase
  - bioconductor-iranges
  - bioconductor-limma
  - bioconductor-rbgl
  - bioconductor-rgraphviz
  - bioconductor-roc
  - bioconductor-rsamtools
  - bioconductor-rtracklayer
  - bioconductor-s4vectors
  - bioconductor-shortread
  - bioconductor-summarizedexperiment
  - bioconductor-systempiper
  - bioconductor-tximport
  - bioconductor-variantannotation
  - bioconductor-xvector
  - bioconductor-zlibbioc
  - cmake
  - curl
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jupyter
  - llvm
  - llvmdev
  - numpy
  - pandas
  - qt
  - r-colorspace
  - r-cowplot
  - r-devtools
  - r-dplyr
  - r-ellipse
  - r-factoextra
  - r-formatr
  - r-formula
  - r-ggfortify
  - r-ggplot2
  - r-ggpubr
  - r-gplots
  - r-gridextra
  - r-gtable
  - r-httpuv
  - r-irkernel
  - r-knitr
  - r-lattice
  - r-leaps
  - r-locfit
  - r-markdown
  - r-nbclust
  - r-openssl
  - r-pkgconfig
  - r-purrr
  - r-rcolorbrewer
  - r-rcurl
  - r-reshape2
  - r-rjson
  - r-rocr
  - r-shiny
  - r-stringi
  - r-stringr
  - r-tibble
  - r-tidyr
  - rpy2
  - scipy
  - tensorboard
  - tensorflow
  - wget